name: Snyk W/ GH Security
on:
  push:
    branches: [ main ]
jobs:
  code-analysis:
    name: Snyk Code Scan & GH security upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Snyk code to check for sast vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: '--severity-threshold=high --sarif-file-output=snyk_sast.sarif'

      - name: Run Snyk open source to check for sast vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: '--severity-threshold=critical --sarif-file-output=snyk_sca.sarif'
          
      - name: Upload sast result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_sast.sarif

      - name: Upload sast result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_sca.sarif